import "./globals.css";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Geist, Geist_Mono, Roboto } from "next/font/google";

import type { Metadata } from "next";
import { DashboardAppBar } from "@/components/app-bar/DashboardAppBar";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import { SessionProvider } from "next-auth/react";
import { AppTheme } from "../components/AppTheme";
import { AuthSnackBar } from "@/components/AuthSnackBar";
import { ModeAwareRenderer } from "@/components/ModeAwareRenderer";
import { auth } from "@/auth";
import { AppStoreContextProvider } from "@/providers/AppStoreContextProvider";
import { DEFAULT_CONFIG, SKELETON_CONFIG } from "@/lib/constants";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const roboto = Roboto({
	weight: ["300", "400", "500", "700"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-roboto",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const getInitialState = async () => {
	const session = await auth();

	if (!session) {
		return {
			appConfig: SKELETON_CONFIG,
		};
	}
	const config = DEFAULT_CONFIG;
	return {
		appConfig: config,
	};
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const initialState = await getInitialState();
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
			>
				<AppRouterCacheProvider>
					<ReactQueryProvider>
						<SessionProvider>
							<AppStoreContextProvider
								initialState={initialState}
							>
								<ModeAwareRenderer>
									<AppTheme>
										<AuthSnackBar />
										<DashboardAppBar />
										{children}
									</AppTheme>
								</ModeAwareRenderer>
							</AppStoreContextProvider>
						</SessionProvider>
					</ReactQueryProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
