import './globals.css';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Geist, Geist_Mono, Roboto } from 'next/font/google';

import type { Metadata } from "next";
import { DashboardContextProvider } from '@/context/DashboardContext';
import { DashboardAppBar } from '@/components/DashboardAppBar';
import { getAppConfig } from '@/lib/actions';
import { getIntialWidgetData } from '@/lib/actions';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialConfig = await getAppConfig();
  console.log(initialConfig);
  const initialWidgetData = await getIntialWidgetData(initialConfig);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <DashboardContextProvider initialConfig={initialConfig} initialWidgetData={initialWidgetData}>
            <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '8px 16px 0' }}>
              <DashboardAppBar />
            </div>
            {children}
          </DashboardContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
