server:
  port: 5000

ui:
  theme: light
  pages:
    - title: Home
      path: /
      columns:
        - size: 2
          widgets:
            - type: weather
              location: Ho Chi Minh City
        - size: 6
          widgets:
            - type: tabs
              labels:
                - r/compsci
                - r/rust
                - r/vozforums
                - r/dataengineering
                - r/leetcode
              tabs:
                - type: reddit
                  subreddit: compsci
                  hideTitle: true
                  sort: new
                  limit: 5
                - type: reddit
                  subreddit: rust
                  hideTitle: true
                  sort: new
                  limit: 5
                - type: reddit
                  subreddit: vozforums
                  hideTitle: true
                  sort: new
                  limit: 5
                - type: reddit
                  subreddit: dataengineering
                  hideTitle: true
                  sort: new
                  limit: 5
                - type: reddit
                  subreddit: leetcode
                  hideTitle: true
                  sort: new
                  limit: 5
